### ISSUE TITLE
Example App

### ISSUE THREAD

**Issue by MRL-00** [cholojuanito/stripe_dart_flutter#4]
Hi guys

Can you please supply an example app for this Flutter Plugin?

Thanks.

**Comment by cholojuanito** [comment]
@MattL-NZ
That's the plan once we have the whole API completely functional. We are still in pre release but we are working hard to get the essentials working first

**Comment by MRL-00** [comment]
Thanks @cholojuanito.
You don't happen to have a rough estimated date on when you think it might be ready for use in a production app?

**Comment by cholojuanito** [comment]
Sadly we don't know since we just started this week, if you would like to help us that would be wonderful

**Comment by nicholasbulka** [comment]
How is this progressing? Can I help in any way?

**Comment by MRL-00** [comment]
@cholojuanito Are you guys still working on this? Haven't seen any commits since May 2019. Can we help?

**Comment by cholojuanito** [comment]
@MattL-NZ
Hey sorry I've been on vacation the last 3 weeks. Also we probably won't be doing anything with it since we decided to go with a different payments API for our app. We might pick it up again if we need credit card payments.

Feel free to fork it and do your own
