### ISSUE TITLE
Null-safety library bumps

### ISSUE THREAD

**Issue by devbrandonlong** [cholojuanito/stripe_dart_flutter#5]
Hello! 

Thank you for making this library @cholojuanito!

Could you possibly bump the `http` & `logging` library versions to their latest versions? The current version range is conflicting with other libraries in one of my apps due to the null-safety additions.

Thank you!

**Comment by cholojuanito** [comment]
So I actually haven't worked on this repo in a long time and I guess I forgot to mark it as archived. We have it marked as discontinued on pub.dev but if you want to work on it in your forked repo that would probably be best
